### ISSUE TITLE
Helmsman does not support any order of YAML state configuration

### ISSUE THREAD

**Issue by jburandt** [mkubaczyk/helmsman#183]
**Edit: Not a helmsman issue. Closing.**

We generate or modify YAML deployment files automatically that get read and used by helmsman, and by default a tool like viper will write YAML in alphabetical order. 

However, even if all of the desired spec options are there, helmsman will not read them correctly. I'm wondering if that's because it's not built to unmarshal YAML out of order?

Error:
```
2019/02/03 18:42:16 INFO: Parsed YAML [[ deployments.yaml ]] successfully and found [ 4 ] apps. 

2019/02/03 18:42:16 ERROR: settings validation failed -- no settings table provided in state file.

```

Deployment YAML with changed names:
```
apps:
  app-1:
    chart: app-1
    enabled: true
    name: app-1
    namespace: app-deploy
    priority: -100
    purge: true
    setstring:
      tag: 0.1.0-qa.66_1f37ebe
    test: false
    tillernamespace: app-deploy
    valuesfile: app-1.yaml
    version: 0.1.11
  app-2:
    chart: app-2
    enabled: true
    name: app-2
    namespace: app-deploy
    priority: -100
    purge: true
    setstring:
      tag: 0.1.0-dev.66_1f37ebe
    test: false
    tillernamespace: app-deploy
    valuesfile: app-2.yaml
    version: 0.1.11
  app-3:
    chart: app-3
    enabled: true
    name: app-3
    namespace: app-deploy
    priority: -100
    purge: true
    setstring:
      tag: 0.1.0-dev.66_1f37ebe
    test: false
    tillernamespace: app-deploy
    valuesfile: app-3.yaml
    version: 0.1.11
helmrepos:
  stable: https://kubernetes-charts.storage.googleapis.com
  local: http://127.0.0.1:8080
metadata:
  description: Desired State File for app-deploy environment.
  maintainer: <snipped>
  org: <snipped>
namespaces:
  kube-system:
    installedtiller: false
    protected: true
  app-deploy:
    protected: false
    usetiller: true
settings:
  kubecontext: aws
  storagebackend: secret
```
